[environment]
python-version = "3.10"
python-platform = "linux"

[src]
include = [
    "contree_sdk/**/*.py",
    "tests/**/*.py",
    "scripts/**/*.py",
]
exclude = [
    "tests/unit/docs/_tmp/**",
    ".venv/**",
    "dist/**",
]

[analysis]
respect-type-ignore-comments = true

[[overrides]]
include = ["**/tests/**/*.py", "**/test_*.py", "**/*_test.py", "**/conftest.py"]
rules.too-many-positional-arguments = "warn"

[[overrides]]
include = ["contree_sdk/_internals/client/**"]
rules.empty-body = "ignore"

[[overrides]]
include = ["tests/e2e/sdk/run/**"]
rules.unsupported-operator = "warn"
