[project]
name = "contree-sdk"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12, <3.14"
dependencies = [
    "httpx",
    "pydantic>=2.11.1",
]

[project.optional-dependencies]
dev = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["contree_sdk"]
