[pytest]
testpaths =
    tests
    README.md
markers =
    e2e: tests that go to real endpoints
    markdown: examples inside md files
addopts =
    -m 'not e2e' -s
    --markdown-docs
    --ignore=README.FUTURE.md
;    -n auto

asyncio_mode = auto
