name: Publish to PyPI

on:
  push:
    branches:
      - main
      - fix/pre-release-fixes

permissions:
  contents: read
  id-token: write

jobs:
  check-required-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for checks-complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'checks-complete'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          running-workflow-name: 'check-required-workflows'
          allowed-conclusions: success

      - name: Wait for tests-complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'tests-complete'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          running-workflow-name: 'check-required-workflows'
          allowed-conclusions: success

      - name: Wait for security-complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'security-complete'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          running-workflow-name: 'check-required-workflows'
          allowed-conclusions: success
  publish:
    needs: check-required-workflows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pipx install uv

      - name: Build
        run: uv build

      - name: Publish via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
