name: Publish to PyPI

on:
  push:
    branches:
      - main
      - fix/pre-release-fixes

permissions:
  contents: read
  id-token: write

jobs:
  check-required-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for checks-complete
        uses: Sibz/await-status-action@v1
        with:
          contexts: checks-complete
          authToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for tests-complete
        uses: Sibz/await-status-action@v1
        with:
          contexts: tests-complete
          authToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for security-complete
        uses: Sibz/await-status-action@v1
        with:
          contexts: security-complete
          authToken: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: check-required-workflows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pipx install uv

      - name: Build
        run: uv build

      - name: Publish via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
