name: RTD docs

on: [pull_request, workflow_dispatch]

jobs:
  deploy-rtd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pipx install uv
      - run: uv run --all-extras sphinx-build docs docs/_build/html

      - name: Write rclone config
        shell: bash
        run: |
          mkdir -p "$GITHUB_HOME/.config/rclone"
          cat > "$GITHUB_HOME/.config/rclone/rclone.conf" <<EOF
          [s3]
          type = s3
          provider = Other
          access_key_id = ${{ secrets.RCLONE_CONFIG_S3_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.RCLONE_CONFIG_S3_SECRET_ACCESS_KEY }}
          endpoint = ${{ secrets.RCLONE_CONFIG_S3_ENDPOINT }}
          region = ${{ secrets.RCLONE_CONFIG_S3_REGION }}
          EOF

      - uses: andreiio/rclone-action@v1
        with:
          args: >
            sync docs/_build/html
            s3:${{ secrets.RCLONE_CONFIG_S3_BUCKET }}/pr/${{ github.event.pull_request.number }}
            --delete-during -v
