name: Security checks

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pipx install uv
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v5
        with:
          path: .venv
          key: venv-dev-security-extra-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('uv.lock', 'pyproject.toml')}}

      - name: Run Semgrep
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: |
          uv run --extra dev-security semgrep ci

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        run: |
          docker run -v ${PWD}:/path ghcr.io/gitleaks/gitleaks:latest \
            detect \
            --source="/path" \
            --redact
